Repository GSG-G13/AhmedAbdallah, pull requests merged in 2023-03, with the labels that each got.

#5 File Structure
  css/style.css
  index.html
  js/app.js
Labels: completed

#8 search system in the site
  css/main.css
  index.html
  js/app.js
Labels: Done

#10 Edit in the code files
  README.md
  css/main.css
  index.html
  js/app.js
Labels: Done

#12 add weather api section in addition to some edits in the styling
  css/main.css
  css/weather_style.css
  images/sun-cloudy-fill.png
  images/sun-fill.png
  images/sun-line (1).png
  images/sun-line.png
  images/weather_background.jpg
  index.html
  js/weather.js
  weather.html
  weather_Pics/sun-cloudy-fill.png
  weather_Pics/sun-fill.png
  weather_Pics/sun-line.png
Labels: awaiting-review

#18 Delete unnecessary files
  README.md
  css/style.css
  ind2ex.html
  js/index.js
  js/script.js
  style.css
  weather_Pics/sun-cloudy-fill.png
  weather_Pics/sun-fill.png
  weather_Pics/sun-line.png
Labels: completed

#19 readme
  README.md
Labels: completed
